### PR TITLE
#8 Add to Dryville main text

### PR DESCRIPTION
**Pull request by tworr**
Adding "Getting Water to Your Homes" and "Dryville's First Water Works" sections to text.

### CODE REVIEW

**Comment by lindsayplatt** [comment]
Do they instructions for #8 say to reference the issue number? Just want to double check

**Comment by tworr** [comment]
They do.  I probably should have added it in the PR description as well.

**Comment by lindsayplatt** [comment]
Is it clear that that's what we are looking for? Not saying you need to do it, just want to make sure it would make sense to a newbie

**Comment by tworr** [comment]
Just double checked and it does specifically say to add the issue # to the description.  I'm just bad at following directions and put it in the title :)

**Pull request merged**
